name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README.md
        - API Documentation (docs/API.md)
        - User Guide (docs/USER_GUIDE.md)
        - Technical Docs (docs/TECHNICAL.md)
        - Contributing Guide (CONTRIBUTING.md)
        - Brand Guidelines
        - Code Comments
        - AI Instructions (.ai/)
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's Wrong or Missing?
      description: Describe the issue with current documentation
      placeholder: "The documentation doesn't explain..."
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where in the documentation is this issue? (file path, section, line number)
      placeholder: "docs/API.md, line 45"
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should we improve this documentation?
      placeholder: "It would be clearer if..."
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of issue is this?
      options:
        - Missing information
        - Incorrect information
        - Outdated information
        - Unclear explanation
        - Missing examples
        - Typo or grammar
        - Formatting issue
        - Broken link
        - Other
    validations:
      required: true

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Willing to Contribute?
      description: Would you like to submit a PR to fix this?
      options:
        - "Yes, I can submit a PR"
        - "Yes, with guidance"
        - "No, but I can review"
        - "No"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the documentation issue
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have checked if this is already documented elsewhere
          required: true
        - label: I have provided specific location information
          required: true
