name: Feature Request
description: Suggest a new feature or enhancement for TangentCore
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module should this feature be added to?
      options:
        - Janitor Module (Shared Drive Cleaner)
        - Brand Module
        - Site Ops Module
        - TangentCore Library
        - UI/Sidebar
        - New Module
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: |
        Who: As a [user type]
        What: I want to [action]
        Why: So that I can [benefit]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: "I've considered..."
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples or Mockups
      description: If applicable, add mockups, screenshots, or links to similar features
      placeholder: Drag and drop images or paste links...
    validations:
      required: false

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Willing to Contribute?
      description: Would you be willing to contribute this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, with guidance"
        - "No, but I can help test"
        - "No"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature aligns with TangentCore's purpose
          required: true
        - label: I have provided a clear use case
          required: true
